spring:
  aop:
    auto: true

#  profiles:
#    active: dev
  #    proxy-target-class: true

  datasource:
    #主数据源，默认的
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_temp
    username: root
    password: 12345678

    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 检测连接是否有效的sql
      validation-query: SELECT 'X'
      validation-query-timeout: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # PSCache Mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: -1
      pool-prepared-statements: false
      filters: stat,wall,log4j2




      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      #启动项目后访问 http://127.0.0.1:8080/druid
      #是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/swagger*"
        #缺省sessionStatMaxCount是1000个
        web-stat-filter.session-stat-max-count: 1000
        #关闭session统计功能
        session-stat-enable: false
        #配置principalSessionName，使得druid能够知道当前的session的用户是谁
        #如果你session中保存的是非string类型的对象，需要重载toString方法
        principalSessionName: xxx.user
        #如果user信息保存在cookie中，你可以配置principalCookieName，使得druid知道当前的user是谁
        principalCookieName: xxx.user
        #druid 0.2.7版本开始支持profile，配置profileEnable能够监控单个url调用的sql列表。
        profile-enable: false

      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      #启动项目后访问 http://127.0.0.1:8080/druid
      #是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        urlPattern: /druid/*
        #禁用HTML页面上的“Reset All”功能
        resetEnable: false
        #用户名
        loginUsername: admin
        #密码
        loginPassword: admin
        #IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.163.1
        #IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Redis数据库索引
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 30000ms
        max-idle: 30
        min-idle: 0
    timeout: 1000ms
#    lettuce:
#      pool:
#        max-wait: 3000ms
#        max-active: 100
#        max-idle: 30
#        min-idle: 0
#      shutdown-timeout: 1000ms


server:
  port: 8888
  servlet:
    context-path: /aopdemo
logging:
  level: {root: info, com.hly: debug}
  file:
    name: log.log



# help link: https://pagehelper.github.io/docs/howtouse/
pagehelper:
  reasonable: true
#  dialect: mysql                    #分页插件方言选择
  support-methods-arguments: true   #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  params: count=countSql
  row-bounds-with-count: true     #默认值为false，该参数对使用 RowBounds 作为分页参数时有效。 当该参数设置为true时，使用 RowBounds 分页会进行 count 查询。
  offset-as-page-num: true        #默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。 当该参数设置为 true 时，会将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数进行分页。
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件位置，classpath指resources
  type-aliases-package: com.exercise.model       #实体类所在位置
  configuration:                            #打印sql到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



